version: "3.7"
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - /var/docker_data/webchat-mongo:/data/db
        restart: always
    web:
        build: .
        ports:
            - 4321:4321
        depends_on:
            - mongo
        restart: always
